package com.emallspace.social.controller;

import com.emallspace.social.entity.Post;
import com.emallspace.social.service.impl.PostService;
import lombok.Data;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/posts")
public class PostController {

    @Autowired
    private PostService postService;

    @PostMapping
    public Post createPost(@RequestBody PostRequest request) {
        return postService.createPost(
            request.getUserId(),
            request.getTitle(),
            request.getContent(),
            request.getImageUrls(),
            request.getTopicId()
        );
    }

    @Data
    public static class PostRequest {
        private Long userId;
        private String title;
        private String content;
        private List<String> imageUrls;
        private Long topicId;
        
        // Getters and Setters generated by Lombok @Data
    }
}
